### ISSUE TITLE
[ASTPP] Customer CDRs and Summary Report issue in ASTPP V3.0

### ISSUE THREAD

**Issue by Amitzz** [iNextrix/ASTPP#199]
Hi 
I am running latest ASTPP 3.0 on Debian

Current bug I found is 

Under 
Call reports => Detailed Reports -> Customer (not working)
                                               -> Reseller    (Note Tested)
                                               -> Provider Outbound ( WORKING )
                 => Summary Report -> Customer ( not working )
                                                -> Reseller    (Note Tested)
                                                -> Provider (not working)

Tried update.sh but no improvement

Regards
AmitZ

**Comment by rayedbs** [comment]
no brother , it is working!
the only bug is in reseller portal!
this bug https://github.com/iNextrix/ASTPP/issues/197
but no one give us a answer!

**Comment by smrdoshi** [comment]
Hi Guys,

@Amit, We must need to look into your srever in order to check that issue
as that is not a bug of open source. It must be something with your setup
or packets.

@Rayed, That issue in queue. Currently team is busy in commercial projects.
As soon as we will get time, we will fix that and update the source code.


Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by rayedbs** [comment]
Thank you Samir Doshi

**Comment by Amitzz** [comment]
Thank you Samir for reply!

Call reports => Detailed Reports -> Customer (not working)
-> Reseller (Tested - not working)
-> Provider Outbound ( WORKING )
=> Summary Report -> Customer ( not working )
-> Reseller (Tested - not working )
-> Provider (not working)

Customer is able to see CDRs after login. Reseller and Admin couldnt able to see customer and summary report.

Can you please list php files of ASTPP which need to investigate.

Thanks
AmitZ

**Comment by Amitzz** [comment]
I have below updates after copying new phps related to reports from astpp git hub

Call reports => Detailed Reports -> Customer (not working)
-> Reseller (Tested - WORKING)
-> Provider Outbound ( WORKING )
=> Summary Report -> Customer ( not working )
-> Reseller (Tested - not working )
-> Provider (not working)

Summary reports at all not working

ASTPP team please assist. Also let me know if you need any logs or any data.

Thanks & Regards
AmitZ

**Comment by Amitzz** [comment]
Hi,

Tried reinstall but still summary reports and customer details reports not working.

Only Able to details reports RESELLER and PROVIDER OUTBOUND

Regards
AmitZ

**Comment by smrdoshi** [comment]
Hi Amit,

As we mentioned previously, we are not sure what is the problem in your
setup.
Lets do one thing, send me your server information off the list. We will
check.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by Amitzz** [comment]
Hi Samir,

I have reinstalled Debian and ASTPP fixed the reports issue.

The ASTPP logs still showing one error

ERROR - 2017-05-23 13:33:01 --> Severity: 8192  --> mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead /var/www/html/astpp/system/database/drivers/mysql/mysql_driver.php 75

Freeswitch CLI shows below error
Error in my_thread_global_end(): 2 threads didn't exit

regards
amitz

**Comment by Amitzz** [comment]
One point I want to mention. I have removed APACHE2 completely this time as I have used nginx

Working all reports now 


Regards
AmitZ.
