### ISSUE TITLE
call not seen by ASTPP

### ISSUE THREAD

**Issue by jihoo05** [iNextrix/ASTPP#214]
When I use GMS gold dialer app ASTPP not able to deduct my customer balance however call was successful. Viewing from freeswitch console no log activity is showing while call is in progress.

GMS gold dialer --> GMS gold dialer = call success but no deduct on customer balance
ASTPP dialer --> ASTPP dialer = call success able to deduct on customer balance
ASPP dialer --> GMS gold dialer = call success able to deduct on customer balance

**Comment by smrdoshi** [comment]
ASTPP doesn't have to do anything with Dialer to do billing. If the call
hangup correctly then billing must be done.
Enable the debug log and check logs in /var/log/astpp/.




<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=samir.doshi@inextrix.com&idSignature=22>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by jihoo05** [comment]
calls were hangup correctly but the customer balance still unchanged no decrease in balance. I do think its a bug, if all subscribers will be using GMS as their dialer they can skipped being charged try to see it for yourself. I did enable my logs as you mention no logs is shown. 

https://play.google.com/store/apps/details?id=com.gmsdialergold.GUI

**Comment by smrdoshi** [comment]
We tried using same dialer and it worked fine.

Now about your issue, make sure to have write permission to /var/log/astpp/
folder. If you have set call debug option true from system configuration
then it must start writing logs for the call.

We must need logs in order to help you to debug the issue which you are
facing.




<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=samir.doshi@inextrix.com&idSignature=22>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by jihoo05** [comment]
I already set the permission, but still cannot see logs. I am using ver 3.0 with nginx

**Comment by smrdoshi** [comment]
That's strange. Create log file astpp.log manually and check. To debug your issue, we must require logs.

**Comment by smrdoshi** [comment]
No feedback. Closing the issue.
