### ISSUE TITLE
SIP devices and IP settings are orphaned after deleting account

### ISSUE THREAD

**Issue by powerpbx** [iNextrix/ASTPP#401]
There are probably other settings that are orphaned as well.

So it appears that deleting an account only makes all the related settings disappear from the GUI but not the DB.  This creates problems when trying to add new settings as they will fail validation if they have the same SIP username or IP etc.

**Comment by smrdoshi** [comment]
When you delete an account, we are deleting records from all modules which belong to that account except for accounts and cdrs. For account, we do soft delete which means only flag will be changed and it will disappear from the UI. 

The purpose to do soft delete of account and to keep CDR is, in many countries admin need to keep cdr records for all the customers for few months or years. Now if we hard delete those records then admin might be in trouble. To avoid that issue, we implemented soft delete concept. 

Now regarding your point for sip device and ip settings, I just tested it in version 3.6 and I am not facing any problem. I am able to create same sip device and ip settings. 

If you are still facing the problem then highlight the exact issue.

**Comment by powerpbx** [comment]
Create a customer account and add a sip device.  Now delete that customer account.

Now create another customer account and try dd a sip device with the exact same name.  It will fail validation because that same sip device name still exists in the database.

I believe the same thing will happen if you add IP Settings to an account and then delete account and then try add the same IP again to a different account.

**Comment by smrdoshi** [comment]
Just tried same thing which you mentioned and it worked without any
problem.

Here is the video of it : http://nimb.ws/BqpSnb



‌
[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance on the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by powerpbx** [comment]
That video shows you deleting a customer device.  Not a provider device.
